#!/bin/sh
# Author: Mark D. Blackwell
# Date written: December 29, 2010
# Date last changed: December 29, 2010

# Usage:
#   combine `<command>` [...]
# Usage example:
#   combine `./pathr .*file_a.*` `./grep-files filea`

#for arg in $@ ; do echo $arg ; done | sort | uniq
#for arg in $@ ; do echo `$arg` ; done | sort | uniq
#for arg in $@ ; do `echo $arg` ; done | sort | uniq
#echo `./trees $1`'
#'`./base $1` | sort | uniq
#echo `for arg in $@ ; do `$arg'
#'` ; done | sort | uniq
echo 'Not working.'

