#!/bin/sh
# Author: Mark D. Blackwell
# Date written: October 29, 2010
# Date last changed: October 29, 2010

# Edit (in nano) all files new or modified since the last commit.
# Usage (in any directory under Git versioning):
#   dnano

nano `git-diff --name-only HEAD`
