#!/bin/sh
# Author: Mark D. Blackwell
# Date written: November 5, 2010
# Date last changed: November 6, 2010

# Usage:
#   grep-files <regexp>

grep --exclude=*\.sqlite3 \
--exclude-dir=\.git \
--exclude-dir=db \
--exclude-dir=javascripts \
--exclude-dir=log \
--exclude-dir=migrate \
--exclude-dir=out \
--exclude-dir=vendor \
--recursive --files-with-matches --regexp=$1 .
# By hand:  grep -rle <regexp> <directory>
