#!/bin/sh
# Author: Mark D. Blackwell
# Date written: December 21, 2010
# Date last changed: December 21, 2010
# Find files matching a pathname regular expression.
# Usage:
#   pathr <pathname-regular-expression>
# Example usage:
#   pathr '.*\.yml'
#   pathr '.*tag.*'
#   pathr 'app/.*/_?pic.*'
find test app -regex $1 -type f | sort
