#!/bin/sh
# Author: Mark D. Blackwell
# Date written: December 21, 2010
# Date last changed: January 15, 2011
# Find files matching a pathname regular expression.
# Usage:
#   pathr <pathname-regular-expression>
# Usage examples:
#   pathr '.*\.yml'
#   pathr '.*tag.*'
#   pathr 'app/.*pic.*'
#   pathr 'app/.*/_?pic.*'
#   pathr '.*(get_f|rs/ses|ls/dir|file_t).*'
#   pathr '.*(get_f|rs/ses|ls/(dir|file_t)).*'
find test app -regextype posix-egrep -regex $1 -type f | sort
