#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

# $:.push("/home/meganamo/ruby/lib").push("/home/meganamo/ruby/gems/gems")
# require '/home/meganamo/ruby/gems/gems/bundler-1.0.10/lib/bundler.rb'

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'rails/commands'
